### ISSUE TITLE
Make cm-janus as define

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1196]
Currently `cm-janus` on start-up will verify if `cm-app` responses on defined RPC interface. If check fails then `cm-janus` exits.

**Comment by kris-lab** [comment]
@tomaszdurka as follow up for our chat... would we great if you share your ideas about `cm-janus` here! thx

**Comment by kris-lab** [comment]
I have tried with simple web server, however it is not working because `nginx` does not allow for `CM_Janus_RpcEndpoints.removeAllStreams` as HTTP request `method`. It works if we proxy the request from `nginx` to `php-fpm`. Configuring `nginx` with accepting any method will require changes to core module.

An ideas?

**Comment by kris-lab** [comment]
@tomaszdurka @ppp0 @njam any idea?

**Comment by njam** [comment]
Not sure if I understand the exact problem. This request is of method "POST", and has additionally a field `method` in its body, with the value "CM_Janus_RpcEndpoints.removeAllStreams".
See https://github.com/cargomedia/cm-janus/blob/fd4eecc003e03b2fe8a8a0e241b6d326f88bdcc5/lib/cm-api-client.js#L26

The CM endpoint actually accepts both POST and GET. See https://github.com/cargomedia/cm/blob/master/library/CM/Http/Response/RPC.php

**Comment by kris-lab** [comment]
Agree in general. Please have a look:

options we send:
```
{ method: 'POST',
  uri: 'http://www.cm.dev',
  body: 
   { method: 'CM_Janus_RpcEndpoints.removeAllStreams',
     params: [ 'cm-fish' ] },
  json: true }
```

output
```
[2016-03-07 08:23:12.998] [INFO] [default] - cm-api request http://www.cm.dev { method: 'CM_Janus_RpcEndpoints.removeAllStreams',
  params: [ 'cm-fish' ] }
[2016-03-07 08:23:13.013] [DEBUG] [default] - HTTP server on port 8100 started
[2016-03-07 08:23:13.033] [ERROR] [default] - Process failed. Exiting. Error: cm-api error: 405 - <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at /usr/lib/node_modules/cm-janus/lib/cm-api-client.js:42:13
    at tryCatcher (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/cm-janus/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
[2016-03-07 08:23:13.037] [INFO] [default] - Closing application
```

**Comment by kris-lab** [comment]
I have simple server which return `{}`. Output of `curl`:
```
curl -I http://www.cm.dev
HTTP/1.1 200 OK
Content-Length: 2
ETag: "56dd33a2-2"
Date: Mon, 07 Mar 2016 08:25:06 GMT
Last-Modified: Mon, 07 Mar 2016 07:54:10 GMT
Server: nginx
Content-Type: text/html; charset=utf-8
Accept-Ranges: bytes
Age: 53
Connection: keep-alive
```

```
curl http://www.cm.dev
{}
```

Not sure how to fake it easily?

**Comment by njam** [comment]
Looks like a normal nginx server - serving static files - does not accept POST requests.

Common workaround is to route 405 errors to the 200 page:
http://leandroardissone.com/post/19690882654/nginx-405-not-allowed

**Comment by kris-lab** [comment]
Makes sense! I was doing POST to the static file. Will try to find a workaround.

**Comment by tomaszdurka** [comment]
Sounds ok for me. I am still not sure if cm-janus should really fail when cm is not available.

**Comment by njam** [comment]
As discussed let's keep cm-janus' behaviour, and mock the CM RPC endpoint in the puppet specs.

**Comment by njam** [comment]
done
