### ISSUE TITLE
Support multi-line syslog entries in fluentd

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1241]

**Comment by ppp0** [comment]
This is a weird requirement. Multi-line syslog entries are not covered by [RFC 5424](https://tools.ietf.org/html/rfc5424), `logger` does not allow for it, a process can spit out several log entries.

What is generating multiliners?

**Comment by njam** [comment]
You're right:
```
2016-04-06T14:32:01.033360+00:00 bulldog3 puppet-agent[14917]: Could not retrieve catalog; skipping run
2016-04-06T14:32:01.160712+00:00 bulldog3 puppet[10051]: /usr/lib/ruby/vendor_ruby/puppet/agent.rb:87:in `exit': no implicit conversion from nil to integer (TypeError)
2016-04-06T14:32:01.161058+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/agent.rb:87:in `block in run_in_fork'
2016-04-06T14:32:01.161253+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/agent.rb:84:in `fork'
2016-04-06T14:32:01.161421+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/agent.rb:84:in `run_in_fork'
2016-04-06T14:32:01.161815+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/agent.rb:43:in `block in run'
2016-04-06T14:32:01.161987+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/application.rb:179:in `call'
2016-04-06T14:32:01.162148+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/application.rb:179:in `controlled_run'
2016-04-06T14:32:01.162306+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/agent.rb:41:in `run'
2016-04-06T14:32:01.162465+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/daemon.rb:163:in `block in run_event_loop'
2016-04-06T14:32:01.162623+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/scheduler/job.rb:49:in `call'
2016-04-06T14:32:01.162788+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/scheduler/job.rb:49:in `run'
2016-04-06T14:32:01.162949+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/scheduler/scheduler.rb:39:in `block in run_ready'
2016-04-06T14:32:01.163109+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/scheduler/scheduler.rb:34:in `each'
2016-04-06T14:32:01.163267+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/scheduler/scheduler.rb:34:in `run_ready'
2016-04-06T14:32:01.163425+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/scheduler/scheduler.rb:11:in `run_loop'
2016-04-06T14:32:01.163583+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/daemon.rb:179:in `run_event_loop'
2016-04-06T14:32:01.163741+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/daemon.rb:142:in `start'
2016-04-06T14:32:01.163903+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/application/agent.rb:378:in `main'
2016-04-06T14:32:01.164062+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/application/agent.rb:324:in `run_command'
2016-04-06T14:32:01.164227+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block (2 levels) in run'
2016-04-06T14:32:01.164388+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/application.rb:507:in `plugin_hook'
2016-04-06T14:32:01.164545+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block in run'
2016-04-06T14:32:01.164702+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/util.rb:488:in `exit_on_fail'
2016-04-06T14:32:01.164860+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `run'
2016-04-06T14:32:01.165022+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:146:in `run'
2016-04-06T14:32:01.165179+00:00 bulldog3 puppet[10051]: from /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:92:in `execute'
2016-04-06T14:32:01.165337+00:00 bulldog3 puppet[10051]: from /usr/bin/puppet:8:in `<main>'
```
