### ISSUE TITLE
[Jenkins] - Test run without failures ends with java exception (and fails)

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1348]
I've seen this on http://ci.cargomedia.ch:8080/job/cargomedia-puppet-packages-pr/195/console where tests were run successfully but somehow tearing down (vagrant?) fails

```sh
Finished in 29 mins 6 secs.
Success! 17 specs run, 0 failures (95 examples, 0 failures)

vagrant halt --force
==> Debian-8: Forcing shutdown of VM...
==> Ubuntu-15.04: Forcing shutdown of VM...
==> Debian-7: Forcing shutdown of VM...
FATAL: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
	at org.jenkinsci.plugins.GithubSecurityRealm.loadUserByUsername(GithubSecurityRealm.java:644)
	at hudson.model.User$UserIDCanonicalIdResolver.resolveCanonicalId(User.java:1050)
	at hudson.model.User.get(User.java:395)
	at hudson.model.User.get(User.java:364)
	at hudson.plugins.git.GitChangeSet.findOrCreateUser(GitChangeSet.java:374)
	at hudson.plugins.git.GitChangeSet.getAuthor(GitChangeSet.java:435)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:350)
	at hudson.model.AbstractBuild.getCulprits(AbstractBuild.java:346)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Setting status of 6402e1b267e1adc3cb57cdcc36810d68661e1122 to FAILURE with url http://ci.cargomedia.ch:8080/job/cargomedia-puppet-packages-pr/195/ and message: 'Build finished. '
Finished: FAILURE
```

Obviously, the whole build is red

**Comment by ppp0** [comment]
Possibly related to https://issues.jenkins-ci.org/browse/JENKINS-34775

**Comment by ppp0** [comment]
Interesting, does not seem to be *always* the case

**Comment by njam** [comment]
I'm on it, but will probably first revert and downgrade again tomorrow :(
https://github.com/cargomedia/puppet-packages/pull/1350
https://github.com/cargomedia/puppet-packages/pull/1345

**Comment by njam** [comment]
Upgraded and verified. SK build succeeds: http://ci.cargomedia.ch:8080/job/cargomedia-sk-pr/392/console
