### ISSUE TITLE
Spec tests failing (gem serverspec update)

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#751]
```
Failures:

  1) Command "logrotate -f /etc/logrotate.d/php5-fpm" exit_status 
     Failure/Error: its(:exit_status) { should eq 0 }
     NoMethodError:
       undefined method `exit_status' for Command "logrotate -f /etc/logrotate.d/php5-fpm":Serverspec::Type::Command
     # ./modules/php5/spec/fpm/spec.rb:12:in `block (2 levels) in <top (required)>'

  2) File "/var/log/php5-fpm/php5-fpm.log.1" should be file
     Failure/Error: it { should be_file }
       expected `File "/var/log/php5-fpm/php5-fpm.log.1".file?` to return true, got false
     # ./modules/php5/spec/fpm/spec.rb:16:in `block (2 levels) in <top (required)>'

  3) File "/var/log/php5-fpm/php5-fpm.log" content should match /error log file re-opened/
     Failure/Error: its(:content) { should match /error log file re-opened/ }
       expected "[17-Oct-2014 02:44:40] WARNING: [pool www] pm.start_servers is not set. It's been set to 75.\n[17-Oct-2014 02:44:40] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful\n\n[17-Oct-2014 02:44:40] WARNING: [pool www] pm.start_servers is not set. It's been set to 75.\n[17-Oct-2014 02:44:40] NOTICE: fpm is running, pid 8502\n[17-Oct-2014 02:44:41] NOTICE: ready to handle connections\n[17-Oct-2014 02:44:41] NOTICE: Finishing ...\n[17-Oct-2014 02:44:41] NOTICE: exiting, bye-bye!\n[17-Oct-2014 02:44:41] WARNING: [pool www] pm.start_servers is not set. It's been set to 75.\n[17-Oct-2014 02:44:41] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful\n\n[17-Oct-2014 02:44:41] WARNING: [pool www] pm.start_servers is not set. It's been set to 75.\n[17-Oct-2014 02:44:41] NOTICE: fpm is running, pid 8710\n[17-Oct-2014 02:44:41] NOTICE: ready to handle connections\n" to match /error log file re-opened/
       Diff:
       @@ -1,2 +1,15 @@
       -/error log file re-opened/
       +[17-Oct-2014 02:44:40] WARNING: [pool www] pm.start_servers is not set. It's been set to 75.
       +[17-Oct-2014 02:44:40] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful
       +
       +[17-Oct-2014 02:44:40] WARNING: [pool www] pm.start_servers is not set. It's been set to 75.
       +[17-Oct-2014 02:44:40] NOTICE: fpm is running, pid 8502
       +[17-Oct-2014 02:44:41] NOTICE: ready to handle connections
       +[17-Oct-2014 02:44:41] NOTICE: Finishing ...
       +[17-Oct-2014 02:44:41] NOTICE: exiting, bye-bye!
       +[17-Oct-2014 02:44:41] WARNING: [pool www] pm.start_servers is not set. It's been set to 75.
       +[17-Oct-2014 02:44:41] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful
       +
       +[17-Oct-2014 02:44:41] WARNING: [pool www] pm.start_servers is not set. It's been set to 75.
       +[17-Oct-2014 02:44:41] NOTICE: fpm is running, pid 8710
       +[17-Oct-2014 02:44:41] NOTICE: ready to handle connections
     # ./modules/php5/spec/fpm/spec.rb:20:in `block (2 levels) in <top (required)>'
```

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/puppet-packages/issues/833
